bd:
  image: postgres
  net: smartclass
  stdin_open: true
  ports:
  - "5432:5432"
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: smartclass
    POSTGRES_DB: smartclass
  
server:
  image: node
  net: smartclass
  working_dir: /home/node_server
  stdin_open: true
  volumes:
  - ./node_server/:/home/node_server
  ports:
  - "3000:3000"
  command: ./start